version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    restart: always
    command: 'azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose'
    ports:
      - "10000:10000"  # Blob storage endpoint
      - "10001:10001"  # Queue storage endpoint
      - "10002:10002"  # Table storage endpoint
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
    driver: local